

--@C:\Users\Sam\Documents\Salon\cleanup_oracle.sql;
@C:\Users\Sam\Documents\Database_labs\Salon\create_salon.sql;
@C:\Users\Sam\Documents\Database_labs\Salon\salon_insert.sql;


-- Show the Name, Type and Price of items (products and services) purchased by each customer sorted by customer lastname
SELECT c.name, 
       p.name, 
       p.type, 
       p.price
FROM product p 
JOIN tran_detail td
  ON p.product_id = td.product_id
JOIN tran t
  ON td.tran_id = t.tran_id
JOIN customer c
  ON c.customer_id = t.customer_id
ORDER BY c.name ASC;

-- Show the total spend of each customer sorted by spend descending
SELECT c.name,
       SUM(td.amount_charged) AS "Total Amount"
FROM product p
JOIN tran_detail td
  ON p.product_id = td.product_id
JOIN tran t
  ON td.tran_id = t.tran_id
JOIN customer c
  ON c.customer_id = t.customer_id
GROUP BY c.name
ORDER BY SUM(td.amount_charged) DESC;

-- Show the total revenue generated by each employee sorted by revenue descending
SELECT e.name,
       SUM(td.amount_charged) AS revenue
FROM tran t
JOIN tran_detail td
  ON td.tran_id = t.tran_id
JOIN employee e
  ON e.employee_id = t.employee_id
GROUP BY e.name
ORDER BY revenue DESC;


-- Show each employee with their title, hire date, manager and manager title
SELECT e1.name,
       e1.title,
       e1.hire_date,
       (SELECT e2.name
        FROM employee e2
        WHERE e1.manager_id = e2.employee_id) AS manager,
       (SELECT e3.title AS title
        FROM employee e3
        WHERE e1.manager_id = e3.employee_id)
FROM employee e1;
   
   
-- Unnormalized Data
SELECT *
FROM customer;

SELECT *
FROM employee;

SELECT * 
FROM location;

SELECT *
FROM product;

SELECT *
FROM tran;

SELECT *
FROM tran_detail;
